name: Deploy Site

env:
  VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
  VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}
  
on:
  push:
    branches: main


jobs:
  Build_and_Deploys_App:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout the latest version of main'
        uses: actions/checkout@v4

      - name: 'Install dependencies'
        run: npm ci

      - name: 'Builds the app'
        run: npm build

      - name: 'Install vercel'
        run: npm install --global vercel@latest

      - name: 'Pull Vercel Env Info'
        run:  vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: 'Build Project Artifacts'
        run:  vercel build --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: 'Deploy Project Artifacts to Vercel'
        run:  vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
  
